# Generated by Django 4.1 on 2022-08-27 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productinventory",
            options={"verbose_name_plural": "product inventories"},
        ),
    ]
