# Generated by Django 4.1 on 2022-08-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_alter_category_slug_alter_product_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttype",
            name="slug",
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
