# Generated by Django 4.1 on 2022-08-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_producttype_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="media",
            options={"verbose_name_plural": "media"},
        ),
        migrations.AlterField(
            model_name="stock",
            name="units",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
