# Generated by Django 4.1 on 2022-08-28 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_product_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productinventory",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_inventory",
                to="inventory.product",
            ),
        ),
    ]
