# Generated by Django 4.1 on 2022-09-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_alter_stock_product_inventory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                choices=[
                    ("decorative", "decorative"),
                    ("commercial", "commercial"),
                    ("fine_art", "fine art"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="name",
            field=models.CharField(
                choices=[
                    ("painting", "painting"),
                    ("sculpture", "sculpture"),
                    ("DIY", "DIY"),
                    ("beadwork", "beadwork"),
                    ("photography", "photography"),
                    ("drawing", "drawing"),
                    ("claywork", "claywork"),
                ],
                max_length=255,
                unique=True,
            ),
        ),
    ]
