# Generated by Django 4.1 on 2022-08-30 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_orderitem_price_alter_orderitem_order_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="price",
            new_name="total_price",
        ),
    ]
